#  exercise for setting up a webserver
- name: Exercise for setting up a webserver apache
  hosts: 3.221.150.90
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup
